// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Repository;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250422193216_UpdateUserSchema")]
    partial class UpdateUserSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("server.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Name = "Павел",
                            Organization = "Telegram",
                            Surname = "Дуров"
                        },
                        new
                        {
                            AuthorId = 2,
                            Name = "Марк",
                            Organization = "Meta",
                            Surname = "Цукерберг"
                        },
                        new
                        {
                            AuthorId = 3,
                            Name = "Сатья",
                            Organization = "Microsoft",
                            Surname = "Наделла"
                        },
                        new
                        {
                            AuthorId = 4,
                            Name = "Сундар",
                            Organization = "Google",
                            Surname = "Пичаи"
                        },
                        new
                        {
                            AuthorId = 5,
                            Name = "Тим",
                            Organization = "Apple",
                            Surname = "Кук"
                        });
                });

            modelBuilder.Entity("server.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ConferenceId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            ConferenceId = 1,
                            Message = "Когда начнется регистрация?",
                            Time = new DateTime(2024, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            ConferenceId = 2,
                            Message = "Будет ли онлайн трансляция?",
                            Time = new DateTime(2024, 3, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            ConferenceId = 3,
                            Message = "Где можно получить материалы конференции?",
                            Time = new DateTime(2024, 3, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 4,
                            ConferenceId = 4,
                            Message = "Какие темы будут обсуждаться?",
                            Time = new DateTime(2024, 3, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 5,
                            ConferenceId = 5,
                            Message = "Нужна ли предварительная регистрация?",
                            Time = new DateTime(2024, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("server.Models.Conference", b =>
                {
                    b.Property<int>("ConferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.HasKey("ConferenceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("ReportId");

                    b.HasIndex("SponsorId");

                    b.ToTable("Conferences");

                    b.HasData(
                        new
                        {
                            ConferenceId = 1,
                            LocationId = 1,
                            Name = "Telegram Conference 2024",
                            OrganizerId = 1,
                            ReportId = 1,
                            SponsorId = 1
                        },
                        new
                        {
                            ConferenceId = 2,
                            LocationId = 2,
                            Name = "Meta Connect Belarus",
                            OrganizerId = 2,
                            ReportId = 2,
                            SponsorId = 2
                        },
                        new
                        {
                            ConferenceId = 3,
                            LocationId = 3,
                            Name = "Microsoft Tech Summit",
                            OrganizerId = 3,
                            ReportId = 3,
                            SponsorId = 3
                        },
                        new
                        {
                            ConferenceId = 4,
                            LocationId = 4,
                            Name = "Google Cloud Next",
                            OrganizerId = 4,
                            ReportId = 4,
                            SponsorId = 4
                        },
                        new
                        {
                            ConferenceId = 5,
                            LocationId = 5,
                            Name = "Apple Developer Day",
                            OrganizerId = 5,
                            ReportId = 5,
                            SponsorId = 5
                        });
                });

            modelBuilder.Entity("server.Models.Confirmed", b =>
                {
                    b.Property<int>("ConfirmationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.HasKey("ConfirmationId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Confirmeds");

                    b.HasData(
                        new
                        {
                            ConfirmationId = 1,
                            Date = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 1
                        },
                        new
                        {
                            ConfirmationId = 2,
                            Date = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2
                        },
                        new
                        {
                            ConfirmationId = 3,
                            Date = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 3
                        },
                        new
                        {
                            ConfirmationId = 4,
                            Date = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 4
                        },
                        new
                        {
                            ConfirmationId = 5,
                            Date = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 5
                        });
                });

            modelBuilder.Entity("server.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Address = "ул. Ленина, 1, Минск",
                            Name = "Конференц-зал 'Минск'"
                        },
                        new
                        {
                            LocationId = 2,
                            Address = "пр. Победителей, 7, Минск",
                            Name = "Бизнес-центр 'Виктория'"
                        },
                        new
                        {
                            LocationId = 3,
                            Address = "ул. Притыцкого, 156, Минск",
                            Name = "IT HUB 'Горизонт'"
                        },
                        new
                        {
                            LocationId = 4,
                            Address = "ул. Сторожевская, 15, Минск",
                            Name = "Отель 'Беларусь'"
                        },
                        new
                        {
                            LocationId = 5,
                            Address = "пр. Независимости, 65, Минск",
                            Name = "Технопарк"
                        });
                });

            modelBuilder.Entity("server.Models.Organizer", b =>
                {
                    b.Property<int>("OrganizerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("OrganizerId");

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            OrganizerId = 1,
                            Name = "Александр",
                            Surname = "Иванов"
                        },
                        new
                        {
                            OrganizerId = 2,
                            Name = "Елена",
                            Surname = "Петрова"
                        },
                        new
                        {
                            OrganizerId = 3,
                            Name = "Михаил",
                            Surname = "Сидоров"
                        },
                        new
                        {
                            OrganizerId = 4,
                            Name = "Анна",
                            Surname = "Козлова"
                        },
                        new
                        {
                            OrganizerId = 5,
                            Name = "Дмитрий",
                            Surname = "Новиков"
                        });
                });

            modelBuilder.Entity("server.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("ConfirmationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("ReportId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ConfirmationId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            AuthorId = 1,
                            ConfirmationId = 1,
                            Description = "Будущее мессенджеров и приватности"
                        },
                        new
                        {
                            ReportId = 2,
                            AuthorId = 2,
                            ConfirmationId = 2,
                            Description = "Метавселенная: новая эра интернета"
                        },
                        new
                        {
                            ReportId = 3,
                            AuthorId = 3,
                            ConfirmationId = 3,
                            Description = "Облачные технологии в 2024"
                        },
                        new
                        {
                            ReportId = 4,
                            AuthorId = 4,
                            ConfirmationId = 4,
                            Description = "Искусственный интеллект в поиске"
                        },
                        new
                        {
                            ReportId = 5,
                            AuthorId = 5,
                            ConfirmationId = 5,
                            Description = "Экосистема Apple и приватность"
                        });
                });

            modelBuilder.Entity("server.Models.Spectator", b =>
                {
                    b.Property<int>("SpectatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSpectators")
                        .HasColumnType("int");

                    b.HasKey("SpectatorId");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Spectators");

                    b.HasData(
                        new
                        {
                            SpectatorId = 1,
                            ConferenceId = 1,
                            NumberOfSpectators = 100
                        },
                        new
                        {
                            SpectatorId = 2,
                            ConferenceId = 2,
                            NumberOfSpectators = 150
                        },
                        new
                        {
                            SpectatorId = 3,
                            ConferenceId = 3,
                            NumberOfSpectators = 200
                        },
                        new
                        {
                            SpectatorId = 4,
                            ConferenceId = 4,
                            NumberOfSpectators = 175
                        },
                        new
                        {
                            SpectatorId = 5,
                            ConferenceId = 5,
                            NumberOfSpectators = 125
                        });
                });

            modelBuilder.Entity("server.Models.Sponsor", b =>
                {
                    b.Property<int>("SponsorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SponsorId");

                    b.ToTable("Sponsors");

                    b.HasData(
                        new
                        {
                            SponsorId = 1,
                            Amount = 10000m,
                            ContactPerson = "Иван Иванов",
                            Email = "microsoft.by@microsoft.com",
                            Organization = "Microsoft Belarus",
                            Phone = "+375291234567"
                        },
                        new
                        {
                            SponsorId = 2,
                            Amount = 15000m,
                            ContactPerson = "Петр Петров",
                            Email = "epam.by@epam.com",
                            Organization = "EPAM Systems",
                            Phone = "+375292345678"
                        },
                        new
                        {
                            SponsorId = 3,
                            Amount = 12000m,
                            ContactPerson = "Алексей Алексеев",
                            Email = "iba.by@iba.com",
                            Organization = "IBA Group",
                            Phone = "+375293456789"
                        },
                        new
                        {
                            SponsorId = 4,
                            Amount = 20000m,
                            ContactPerson = "Сергей Сергеев",
                            Email = "wargaming.by@wargaming.com",
                            Organization = "Wargaming",
                            Phone = "+375294567890"
                        },
                        new
                        {
                            SponsorId = 5,
                            Amount = 18000m,
                            ContactPerson = "Дмитрий Дмитриев",
                            Email = "itechart.by@itechart.com",
                            Organization = "iTechArt Group",
                            Phone = "+375295678901"
                        });
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Адрес администратора",
                            CreatedAt = new DateTime(2025, 4, 22, 19, 32, 16, 350, DateTimeKind.Utc).AddTicks(4294),
                            Email = "admin@example.com",
                            FirstName = "Администратор",
                            LastName = "Системы",
                            MiddleName = "Администраторович",
                            Organization = "Система",
                            PasswordHash = "AQAAAAEAACcQAAAAELbGq7cGxQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQ==",
                            PhoneNumber = "+375291234567",
                            Position = "Администратор",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Тестовый адрес",
                            CreatedAt = new DateTime(2025, 4, 22, 19, 32, 16, 350, DateTimeKind.Utc).AddTicks(4299),
                            Email = "test@example.com",
                            FirstName = "Тестовый",
                            LastName = "Пользователь",
                            MiddleName = "Тестович",
                            Organization = "Тестовая организация",
                            PasswordHash = "AQAAAAEAACcQAAAAELbGq7cGxQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQZQ==",
                            PhoneNumber = "+375297654321",
                            Position = "Тестировщик",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("server.Models.ChatMessage", b =>
                {
                    b.HasOne("server.Models.Conference", "Conference")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("server.Models.Conference", b =>
                {
                    b.HasOne("server.Models.Location", "Location")
                        .WithMany("Conferences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Organizer", "Organizer")
                        .WithMany("Conferences")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Report", "Report")
                        .WithMany("Conferences")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Sponsor", "Sponsor")
                        .WithMany("Conferences")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Organizer");

                    b.Navigation("Report");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("server.Models.Confirmed", b =>
                {
                    b.HasOne("server.Models.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("server.Models.Report", b =>
                {
                    b.HasOne("server.Models.Author", "Author")
                        .WithMany("Reports")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Confirmed", "Confirmed")
                        .WithMany("Reports")
                        .HasForeignKey("ConfirmationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Confirmed");
                });

            modelBuilder.Entity("server.Models.Spectator", b =>
                {
                    b.HasOne("server.Models.Conference", "Conference")
                        .WithMany("Spectators")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("server.Models.Author", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("server.Models.Conference", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Spectators");
                });

            modelBuilder.Entity("server.Models.Confirmed", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("server.Models.Location", b =>
                {
                    b.Navigation("Conferences");
                });

            modelBuilder.Entity("server.Models.Organizer", b =>
                {
                    b.Navigation("Conferences");
                });

            modelBuilder.Entity("server.Models.Report", b =>
                {
                    b.Navigation("Conferences");
                });

            modelBuilder.Entity("server.Models.Sponsor", b =>
                {
                    b.Navigation("Conferences");
                });
#pragma warning restore 612, 618
        }
    }
}
